### ISSUE TITLE
Reform the structure of your project

### ISSUE THREAD

**Issue by bedilbek** [Teo0303/ARMode#1]
@Teo0303 The structure of the project is not consistent with handling static files. It can create an extra headache for DevOps engineer when deploying to a web server or at least it creates inconsistency for other developers who are working in a team to understand the appropriate directory for storing other new static files.

First, you have to create a directory **assets** in the root of the repository and move all of those static files and directories to that new directory. Then, it is better to categorize all of them in **assets** folder according to the type of the static files. For instance, if you have files with **.jpg** or **.png** extension it is better to store them in folder **img** or some other meaningful name for appropriate categorization.

**Comment by Teo0303** [comment]
> @Teo0303 The structure of the project is not consistent with handling static files. It can create an extra headache for DevOps engineer when deploying to a web server or at least it creates inconsistency for other developers who are working in a team to understand the appropriate directory for storing other new static files.
> 
> First, you have to create a directory **assets** in the root of the repository and move all of those static files and directories to that new directory. Then, it is better to categorize all of them in **assets** folder according to the type of the static files. For instance, if you have files with **.jpg** or **.png** extension it is better to store them in folder **img** or some other meaningful name for appropriate categorization.

Thank you for your suggestion.
